// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/cosmos/cosmos-sdk/x/mint/internal/keeper
// ALIASGEN: github.com/cosmos/cosmos-sdk/x/mint/internal/types
package lockproxy

import (
	"github.com/cosmos/gaia/x/lockproxy/internal/keeper"
	"github.com/cosmos/gaia/x/lockproxy/internal/types"
)

const (
	ModuleName        = types.ModuleName
	DefaultParamspace = types.DefaultParamspace
	StoreKey          = types.StoreKey
	QuerierRoute      = types.QuerierRoute
	QueryParameters   = types.QueryParameters
	RouterKey         = types.RouterKey

	AttributeValueCategory = types.AttributeValueCategory

	EventTypeBindProxy           = types.EventTypeBindProxy
	AttributeKeyToChainId        = types.AttributeKeyToChainId
	AttributeKeyToChainProxyHash = types.AttributeKeyToChainProxyHash

	EventTypeBindAsset           = types.EventTypeBindAsset
	AttributeKeySourceAssetDenom = types.AttributeKeySourceAssetDenom
	AttributeKeySourceAssetHash  = types.AttributeKeySourceAssetHash
	AttributeKeyToChainAssetHash = types.AttributeKeyToChainAssetHash
	AttributeKeyInitialAmt       = types.AttributeKeyInitialAmt

	EventTypeLock           = types.EventTypeLock
	AttributeKeyFromAddress = types.AttributeKeyFromAddress
	AttributeKeyToAddress   = types.AttributeKeyToAddress
	AttributeKeyAmount      = types.AttributeKeyAmount

	AttributeKeyFromChainId = types.AttributeKeyFromChainId
	AtttributeKeyStatus     = types.AtttributeKeyStatus

	EventTypeUnlock              = types.EventTypeUnlock
	AttributeKeyFromContractHash = types.AttributeKeyFromContractHash
	AttributeKeyToAssetDenom     = types.AttributeKeyToAssetDenom

	EventTypeCreateLockProxy = types.EventTypeCreateLockProxy
	AttributeKeyCreator      = types.AttributeKeyCreator
	AttributeKeyProxyHash    = types.AttributeKeyProxyHash
	AttributeKeyLockProxy    = types.AttributeKeyLockProxy
)

var (
	// functions aliases
	RegisterCodec           = types.RegisterCodec
	NewKeeper               = keeper.NewKeeper
	NewQuerier              = keeper.NewQuerier
	NewMsgBindAssetParam    = types.NewMsgBindAssetParam
	NewMsgLock              = types.NewMsgLock
	NewQueryProxyHashParams = types.NewQueryProxyHashParams
	NewQueryAssetHashParams = types.NewQueryAssetHashParams
	NewQueryLockedAmtParam  = types.NewQueryLockedAmtParam
	GetBindProxyKey         = keeper.GetBindProxyKey
	GetCrossedAmountKey     = keeper.GetCrossedAmountKey

	// variable aliases
	ModuleCdc                    = types.ModuleCdc
	OperatorKey                  = types.OperatorKey
	ErrInvalidChainId            = types.ErrInvalidChainId
	ErrEmptyTargetHash           = types.ErrEmptyTargetHash
	ErrBelowCrossedLimit         = types.ErrBelowCrossedLimit
	ErrCrossedAmountOverLimit    = types.ErrCrossedAmountOverLimit
	ErrCrossedAmountOverflow     = types.ErrCrossedAmountOverflow
	ErrSupplyKeeperMintCoinsFail = types.ErrSupplyKeeperMintCoinsFail
	BindProxyPrefix              = keeper.BindProxyPrefix
	BindAssetPrefix              = keeper.BindAssetPrefix
	CrossedAmountPrefix          = keeper.CrossedAmountPrefix

	// query balance path
	QueryProxyByOperator = keeper.QueryProxyByOperator
	QueryProxyHash       = keeper.QueryProxyHash
	QueryAssetHash       = keeper.QueryAssetHash
	QueryCrossedAmount   = keeper.QueryLockedAmt
)

type (
	Keeper = keeper.Keeper

	MsgCreateLockProxy = types.MsgCreateLockProxy
	MsgBindProxyHash   = types.MsgBindProxyHash
	MsgBindAssetHash   = types.MsgBindAssetHash
	MsgLock            = types.MsgLock

	TxArgs = types.TxArgs
)
