// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/cosmos/cosmos-sdk/x/mint/internal/keeper
// ALIASGEN: github.com/cosmos/cosmos-sdk/x/mint/internal/types
package ccm

import (
	"github.com/cosmos/gaia/x/ccm/internal/keeper"
	"github.com/cosmos/gaia/x/ccm/internal/types"
)

const (
	ModuleName        = types.ModuleName
	DefaultParamspace = types.DefaultParamspace
	StoreKey          = types.StoreKey
	QuerierRoute      = types.QuerierRoute
	QueryParameters   = types.QueryParameters
	RouterKey         = types.RouterKey

	AttributeValueCategory = types.AttributeValueCategory

	EventTypeCreateCrossChainTx = types.EventTypeCreateCrossChainTx
	AttributeCrossChainId       = types.AttributeCrossChainId
	AttributeKeyTxParamHash     = types.AttributeKeyTxParamHash
	AttributeKeyMakeTxParam     = types.AttributeKeyMakeTxParam

	EventTypeVerifyToCosmosProof                        = types.EventTypeVerifyToCosmosProof
	AttributeKeyMerkleValueTxHash                       = types.AttributeKeyMerkleValueTxHash
	AttributeKeyMerkleValueMakeTxParamTxHash            = types.AttributeKeyMerkleValueMakeTxParamTxHash
	AttributeKeyMerkleValueMakeTxParamToContractAddress = types.AttributeKeyMerkleValueMakeTxParamToContractAddress
	AttributeKeyFromChainId                             = types.AttributeKeyFromChainId
)

var (
	// functions aliases
	RegisterCodec = types.RegisterCodec

	NewKeeper = keeper.NewKeeper

	NewMsgProcessCrossChainTx = types.NewMsgProcessCrossChainTx

	// key function
	GetCrossChainTxKey = keeper.GetCrossChainTxKey
	GetDoneTxKey       = keeper.GetDoneTxKey

	HashToDenom = types.HashToDenom
	DenomToHash = types.DenomToHash
	// variable aliases
	ModuleCdc   = types.ModuleCdc
	OperatorKey = types.OperatorKey

	CurrentChainCrossChainId = types.CurrentChainCrossChainId

	ErrInvalidChainId            = types.ErrInvalidChainId
	ErrEmptyTargetHash           = types.ErrEmptyTargetHash
	ErrBelowCrossedLimit         = types.ErrBelowCrossedLimit
	ErrCrossedAmountOverLimit    = types.ErrCrossedAmountOverLimit
	ErrCrossedAmountOverflow     = types.ErrCrossedAmountOverflow
	ErrSupplyKeeperMintCoinsFail = types.ErrSupplyKeeperMintCoinsFail
)

type (
	Keeper  = keeper.Keeper
	KeeperI = keeper.KeeperI

	MsgProcessCrossChainTx = types.MsgProcessCrossChainTx
	UnlockKeeper           = types.UnlockKeeper
)
