// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/cosmos/cosmos-sdk/x/bank/types
package headersync

import (
	"github.com/cosmos/gaia/x/headersync/internal/keeper"
	"github.com/cosmos/gaia/x/headersync/internal/types"
)

const (
	DefaultCodespace         = types.DefaultCodespace
	CodeSendDisabled         = types.CodeSendDisabled
	CodeInvalidInputsOutputs = types.CodeInvalidInputsOutputs
	ModuleName               = types.ModuleName
	RouterKey                = types.RouterKey
	QuerierRoute             = types.QuerierRoute
	DefaultParamspace        = types.DefaultParamspace

	AttributeValueCategory = types.AttributeValueCategory
	StoreKey                     = types.StoreKey
	EventTypeSyncHeader = types.EventTypeSyncHeader
	AttributeKeyChainId = types.AttributeKeyChainId
	AttributeKeyHeight = types.AttributeKeyHeight
	AttributeKeyBlockHash = types.AttributeKeyBlockHash
	AttributeKeyNativeChainHeight = types.AttributeKeyNativeChainHeight
)

var (
	// functions aliases
	RegisterCodec          = types.RegisterCodec
	ErrNoInputs            = types.ErrNoInputs
	ErrNoOutputs           = types.ErrNoOutputs
	ErrInputOutputMismatch = types.ErrInputOutputMismatch
	ErrSendDisabled        = types.ErrSendDisabled
	NewBaseKeeper          = keeper.NewBaseKeeper
	ParamKeyTable          = types.ParamKeyTable

	NewMsgSyncGenesisParam = types.NewMsgSyncGenesisParam
	NewMsgSyncHeadersParam = types.NewMsgSyncHeadersParam
	NewQueryHeaderParams = types.NewQueryHeaderParams
	NewQueryCurrentHeightParams = types.NewQueryCurrentHeightParams

	// variable aliases
	ModuleCdc                = types.ModuleCdc
	ParamStoreKeySendEnabled = types.ParamStoreKeySendEnabled
	BlockHeaderPrefix = keeper.BlockHeaderPrefix
	BlockCurrentHeightKey = keeper.BlockCurrentHeightKey
	ConsensusPeerPrefix = keeper.ConsensusPeerPrefix
	KeyHeightPrefix = keeper.KeyHeightPrefix





)

type (
	BaseKeeper   = keeper.BaseKeeper // ibc module depends on this
	Keeper       = keeper.Keeper
	MsgSyncHeadersParam      = types.MsgSyncHeadersParam
	MsgSyncGenesisParam = types.MsgSyncGenesisParam
	QueryHeaderParams = types.QueryHeaderParams
	QueryCurrentHeightParams = types.QueryCurrentHeightParams


)
