// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/cosmos/cosmos-sdk/x/mint/internal/keeper
// ALIASGEN: github.com/cosmos/cosmos-sdk/x/mint/internal/types
package btcx

import (
	"github.com/cosmos/gaia/x/btcx/exported"
	"github.com/cosmos/gaia/x/btcx/internal/keeper"
	"github.com/cosmos/gaia/x/btcx/internal/types"
)

const (
	ModuleName        = types.ModuleName
	DefaultParamspace = types.DefaultParamspace
	StoreKey          = types.StoreKey
	QuerierRoute      = types.QuerierRoute
	QueryParameters   = types.QueryParameters
	RouterKey         = types.RouterKey

	AttributeValueCategory = types.AttributeValueCategory

	AttributeKeyToChainId = types.AttributeKeyToChainId

	EventTypeBindAsset           = types.EventTypeBindAsset
	AttributeKeySourceAssetDenom = types.AttributeKeySourceAssetDenom
	AttributeKeyFromAssetHash    = types.AttributeKeyFromAssetHash
	AttributeKeyToChainAssetHash = types.AttributeKeyToChainAssetHash

	EventTypeLock           = types.EventTypeLock
	AttributeKeyFromAddress = types.AttributeKeyFromAddress
	AttributeKeyToAddress   = types.AttributeKeyToAddress
	AttributeKeyAmount      = types.AttributeKeyAmount

	AttributeKeyFromChainId = types.AttributeKeyFromChainId

	EventTypeUnlock              = types.EventTypeUnlock
	AttributeKeyFromContractHash = types.AttributeKeyFromContractHash
	AttributeKeyToAssetDenom     = types.AttributeKeyToAssetDenom

	EventTypeCreateCoin         = types.EventTypeCreateCoin
	AttributeKeyCreator         = types.AttributeKeyCreator
	AttributeKeyRedeemKey       = types.AttributeKeyRedeemKey
	AttributeKeyRedeemScript    = types.AttributeKeyRedeemScript
	AttributeKeySourceAssetHash = types.AttributeKeySourceAssetHash
)

var (
	// functions aliases
	RegisterCodec = types.RegisterCodec
	NewKeeper     = keeper.NewKeeper
	NewQuerier    = keeper.NewQuerier

	NewMsgCreateCoin     = types.NewMsgCreateCoin
	NewMsgBindAssetParam = types.NewMsgBindAssetParam
	NewMsgLock           = types.NewMsgLock

	// variable aliases
	ModuleCdc = types.ModuleCdc

	ErrInvalidChainId         = types.ErrInvalidChainId
	ErrEmptyTargetHash        = types.ErrEmptyTargetHash
	ErrBelowCrossedLimit      = types.ErrBelowCrossedLimit
	ErrCrossedAmountOverLimit = types.ErrCrossedAmountOverLimit
	ErrCrossedAmountOverflow  = types.ErrCrossedAmountOverflow
)

type (
	Keeper          = keeper.Keeper
	DenomInfoWithId = types.DenomInfoWithId
	DenomInfo       = types.DenomInfo

	MsgBindAssetHash = types.MsgBindAssetHash
	MsgCreateCoin    = types.MsgCreateCoin
	MsgLock          = types.MsgLock

	ToBTCArgs = types.ToBTCArgs
	BTCArgs   = types.BTCArgs

	UnlockKeeper = exported.UnlockKeeper
)
