// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/cosmos/cosmos-sdk/x/mint/internal/keeper
// ALIASGEN: github.com/cosmos/cosmos-sdk/x/mint/internal/types
package crosschain

import (
	"github.com/cosmos/gaia/x/crosschain/internal/keeper"
	"github.com/cosmos/gaia/x/crosschain/internal/types"
)

const (
	ModuleName        = types.ModuleName
	DefaultParamspace = types.DefaultParamspace
	StoreKey          = types.StoreKey
	QuerierRoute      = types.QuerierRoute
	QueryParameters   = types.QueryParameters
	RouterKey         = types.RouterKey

	AttributeValueCategory        = types.AttributeValueCategory
	EventTypeSyncHeader           = types.EventTypeSyncHeader
	AttributeKeyChainId           = types.AttributeKeyChainId
	AttributeKeyHeight            = types.AttributeKeyHeight
	AttributeKeyBlockHash         = types.AttributeKeyBlockHash
	AttributeKeyNativeChainHeight = types.AttributeKeyNativeChainHeight

	EventTypeBindProxy           = types.EventTypeBindProxy
	AttributeKeyToChainId        = types.AttributeKeyToChainId
	AttributeKeyToChainProxyHash = types.AttributeKeyToChainProxyHash

	EventTypeBindAsset           = types.EventTypeBindAsset
	AttributeKeySourceAssetDenom = types.AttributeKeySourceAssetDenom
	AttributeKeyFromAssetHash    = types.AttributeKeyFromAssetHash
	AttributeKeyToChainAssetHash = types.AttributeKeyToChainAssetHash

	EventTypeLock           = types.EventTypeLock
	AttributeKeyFromAddress = types.AttributeKeyFromAddress
	AttributeKeyToAddress   = types.AttributeKeyToAddress
	AttributeKeyAmount      = types.AttributeKeyAmount

	EventTypeCreateCrossChainTx = types.EventTypeCreateCrossChainTx
	AttributeCrossChainId       = types.AttributeCrossChainId
	AttributeKeyTxParamHash     = types.AttributeKeyTxParamHash
	AttributeKeyMakeTxParam     = types.AttributeKeyMakeTxParam

	EventTypeVerifyToCosmosProof                        = types.EventTypeVerifyToCosmosProof
	AttributeKeyMerkleValueTxHash                       = types.AttributeKeyMerkleValueTxHash
	AttributeKeyMerkleValueMakeTxParamTxHash            = types.AttributeKeyMerkleValueMakeTxParamTxHash
	AttributeKeyMerkleValueMakeTxParamToContractAddress = types.AttributeKeyMerkleValueMakeTxParamToContractAddress
	AttributeKeyFromChainId                             = types.AttributeKeyFromChainId
	AtttributeKeyStatus                                 = types.AtttributeKeyStatus

	EventTypeUnlock              = types.EventTypeUnlock
	AttributeKeyFromContractHash = types.AttributeKeyFromContractHash
	AttributeKeyToAssetDenom     = types.AttributeKeyToAssetDenom

	EventTypeSetRedeemScript = types.EventTypeSetRedeemScript
	AttributeKeyRedeemKey    = types.AttributeKeyRedeemKey
	AttributeKeyRedeemScript = types.AttributeKeyRedeemScript
)

var (
	// functions aliases
	RegisterCodec = types.RegisterCodec
	NewKeeper     = keeper.NewCrossChainKeeper
	NewQuerier    = keeper.NewQuerier

	NewMsgSyncGenesisParam      = types.NewMsgSyncGenesisParam
	NewMsgSyncHeadersParam      = types.NewMsgSyncHeadersParam
	NewMsgBindProxyParam        = types.NewMsgBindProxyParam
	NewMsgBindAssetParam        = types.NewMsgBindAssetParam
	NewMsgLock                  = types.NewMsgLock
	NewMsgProcessCrossChainTx   = types.NewMsgProcessCrossChainTx
	NewMsgCreateCoins           = types.NewMsgCreateCoins
	NewMsgSetRedeemScript       = types.NewMsgSetRedeemScript
	NewQueryHeaderParams        = types.NewQueryHeaderParams
	NewQueryCurrentHeightParams = types.NewQueryCurrentHeightParams
	NewQueryProxyHashParams     = types.NewQueryProxyHashParams
	NewQueryAssetHashParams     = types.NewQueryAssetHashParams
	NewQueryLockedAmtParam      = types.NewQueryLockedAmtParam

	// key function
	GetBlockHeaderKey      = keeper.GetBlockHeaderKey
	GetBlockHashKey        = keeper.GetBlockHashKey
	GetBlockCurHeightKey   = keeper.GetBlockCurHeightKey
	GetConsensusPeerKey    = keeper.GetConsensusPeerKey
	GetKeyHeightsKey       = keeper.GetKeyHeightsKey
	GetBindProxyKey        = keeper.GetBindProxyKey
	GetBindAssetKey        = keeper.GetBindAssetKey
	GetCrossedLimitKey     = keeper.GetCrossedLimitKey
	GetCrossedAmountKey    = keeper.GetCrossedAmountKey
	GetCrossChainTxKey     = keeper.GetCrossChainTxKey
	GetDoneTxKey           = keeper.GetDoneTxKey
	GetRedeemScriptKey     = keeper.GetRedeemScriptKey
	GetKeyToHashKey        = keeper.GetKeyToHashKey
	GetContractToScriptKey = keeper.GetContractToScriptKey

	ParamKeyTable    = types.ParamKeyTable
	DefaultCoins     = types.DefaultCoins
	ValidateOperator = types.ValidateOperator
	HashToDenom      = types.HashToDenom
	DenomToHash      = types.DenomToHash
	// variable aliases
	ModuleCdc   = types.ModuleCdc
	OperatorKey = types.OperatorKey

	CurrentChainCrossChainId = types.CurrentChainCrossChainId

	ErrInvalidChainId            = types.ErrInvalidChainId
	ErrEmptyTargetHash           = types.ErrEmptyTargetHash
	ErrBelowCrossedLimit         = types.ErrBelowCrossedLimit
	ErrCrossedAmountOverLimit    = types.ErrCrossedAmountOverLimit
	ErrCrossedAmountOverflow     = types.ErrCrossedAmountOverflow
	ErrSupplyKeeperMintCoinsFail = types.ErrSupplyKeeperMintCoinsFail

	BindProxyPrefix          = keeper.BindProxyPrefix
	BindAssetPrefix          = keeper.BindAssetPrefix
	CrossedLimitPrefix       = keeper.CrossedLimitPrefix
	CrossedAmountPrefix      = keeper.CrossedAmountPrefix
	CrossChainIdKey          = keeper.CrossChainIdKey
	CrossChainTxDetailPrefix = keeper.CrossChainTxDetailPrefix
	CrossChainDoneTxPrefix   = keeper.CrossChainDoneTxPrefix
	RedeemKeyScriptPrefix    = keeper.RedeemKeyScriptPrefix

	RedeemToHashPrefix     = keeper.RedeemToHashPrefix
	ContractToRedeemPrefix = keeper.ContractToRedeemPrefix
	BlockHeaderPrefix      = keeper.BlockHeaderPrefix
	BlockHashPrefix        = keeper.BlockHashPrefix
	ConsensusPeerPrefix    = keeper.ConsensusPeerPrefix
	KeyHeightPrefix        = keeper.KeyHeightPrefix

	BlockCurrentHeightKey = keeper.BlockCurrentHeightKey
	QueryHeader           = keeper.QueryHeader
	QueryCurrentHeight    = keeper.QueryCurrentHeight

	// query balance path
	QueryProxyHash     = keeper.QueryProxyHash
	QueryAssetHash     = keeper.QueryAssetHash
	QueryCrossedAmount = keeper.QueryLockedAmt
	QueryOperator      = keeper.QueryOperator
)

type (
	Keeper     = keeper.Keeper
	Operator   = types.Operator
	CoinsParam = types.CoinsParam

	MsgBindProxyParam      = types.MsgBindProxyParam
	MsgBindAssetParam      = types.MsgBindAssetParam
	MsgLock                = types.MsgLock
	MsgProcessCrossChainTx = types.MsgProcessCrossChainTx
	MsgCreateCoins         = types.MsgCreateCoins

	TxArgs = types.TxArgs
)
