// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/cosmos/cosmos-sdk/x/mint/internal/keeper
// ALIASGEN: github.com/cosmos/cosmos-sdk/x/mint/internal/types
package crosschain

import (
	"github.com/cosmos/gaia/x/crosschain/internal/keeper"
	"github.com/cosmos/gaia/x/crosschain/internal/types"
)

const (
	ModuleName        = types.ModuleName
	DefaultParamspace = types.DefaultParamspace
	StoreKey          = types.StoreKey
	QuerierRoute      = types.QuerierRoute
	QueryParameters   = types.QueryParameters

	RouterKey = types.RouterKey
)

var (
	// functions aliases
	RegisterCodec             = types.RegisterCodec
	NewKeeper                 = keeper.NewCrossChainKeeper
	NewQuerier                = keeper.NewQuerier




	NewMsgSyncGenesisParam      = types.NewMsgSyncGenesisParam
	NewMsgSyncHeadersParam      = types.NewMsgSyncHeadersParam
	NewMsgBindProxyParam      = types.NewMsgBindProxyParam
	NewMsgBindAssetParam      = types.NewMsgBindAssetParam
	NewMsgLock                = types.NewMsgLock
	NewMsgProcessCrossChainTx = types.NewMsgProcessCrossChainTx
	NewMsgCreateCoins         = types.NewMsgCreateCoins
	NewQueryHeaderParams        = types.NewQueryHeaderParams
	NewQueryCurrentHeightParams = types.NewQueryCurrentHeightParams
	NewQueryProxyHashParams    = types.NewQueryProxyHashParams
	NewQueryAssetHashParams    = types.NewQueryAssetHashParams
	NewQueryCrossedAmountParam = types.NewQueryCrossedAmountParam
	NewQueryCrossedLimitParam  = types.NewQueryCrossedLimitParam

	ParamKeyTable    = types.ParamKeyTable
	DefaultCoins     = types.DefaultCoins
	ValidateOperator = types.ValidateOperator

	// variable aliases
	ModuleCdc                = types.ModuleCdc
	OperatorKey              = types.OperatorKey

	CurrentChainCrossChainId = types.CurrentChainCrossChainId

	ErrInvalidChainId = types.ErrInvalidChainId
	ErrEmptyTargetHash = types.ErrEmptyTargetHash
	ErrBelowCrossedLimit = types.ErrBelowCrossedLimit
	ErrCrossedAmountOverLimit = types.ErrCrossedAmountOverLimit
	ErrCrossedAmountOverflow = types.ErrCrossedAmountOverflow
	ErrSupplyKeeperMintCoinsFail = types.ErrSupplyKeeperMintCoinsFail

	BindProxyPrefix          = keeper.BindProxyPrefix
	BindAssetPrefix          = keeper.BindAssetPrefix
	CrossedLimitPrefix       = keeper.CrossedLimitPrefix
	CrossedAmountPrefix      = keeper.CrossedAmountPrefix
	CrossChainIdKey          = keeper.CrossChainIdKey
	CrossChainTxDetailPrefix = keeper.CrossChainTxDetailPrefix
	CrossChainDoneTxPrefix   = keeper.CrossChainDoneTxPrefix
	HashToDenom = types.HashToDenom
	DenomToHash = types.DenomToHash
)

type (
	Keeper     = keeper.Keeper
	Operator   = types.Operator
	CoinsParam = types.CoinsParam

	MsgBindProxyParam      = types.MsgBindProxyParam
	MsgBindAssetParam      = types.MsgBindAssetParam
	MsgLock                = types.MsgLock
	MsgProcessCrossChainTx = types.MsgProcessCrossChainTx
	MsgCreateCoins         = types.MsgCreateCoins

	TxArgs = types.TxArgs
)
